[[metric]]
context = "session"
labels = [ "state" ]
metricsdesc = { value= "Gauge metric with count of state sessions by DmService." }
request = "select count(*) as value , state  from v$sessions group by  state;"

[[metric]]
context = "session"
metricsdesc = { max= "Gauge metric with count of  sessions by DmService." }
request = " SELECT PARA_VALUE as max FROM v$dm_ini WHERE PARA_NAME='MAX_SESSIONS';"



[[metric]]
context = "tablespace"
labels = [ "tablespace_name" ]
metricsdesc = { free_space = "Generic counter metric of tablespaces free space MB in DmService.", total_space = "Generic counter metric of tablespaces total space MB in DmService.", free_percent = "Generic counter metric of tablespaces free percent in DmService." }
request = '''
select
t.name tablespace_name,
sum(d.free_size*SF_GET_PAGE_SIZE()/1024/1024)  free_space,
sum(d.total_size*SF_GET_PAGE_SIZE()/1024/1024)  total_space,
sum(d.free_size*100)/sum(d.total_size)  free_percent
from
v$tablespace t,
v$datafile d
where
t.id=d.group_id
group by t.name;
'''

[[metric]]
context = "systeminfo"
metricsdesc = { n_cpu= "cpu 个数.",total_phy_size= "物理内存总大小.", free_phy_size= "剩余物理内存大小.", total_disk_size= "磁盘总大小.", free_disk_size= "剩余磁盘大小.", load_one_average= "每分钟平均负载.", load_five_average= "每五分钟平均负载.", load_fifteen_average= "每十五分钟平均负载.", cpu_user_rate= "用户级的 cpu 使用率.", cpu_system_rate= "系统级的 cpu 使用率.", cpu_idle_rate= "idle 的 cpu 使用率.",  send_bytes_per_second= "当前每秒发送字节数.", receive_bytes_per_second= "当前每秒接收字节数.",send_bytes_total="发送的总字节数.",receive_bytes_total="接收的总字节数." }
request = " select n_cpu,total_phy_size,free_phy_size,total_disk_size,free_disk_size,load_one_average,load_five_average,load_fifteen_average,cpu_user_rate,cpu_system_rate,cpu_idle_rate,send_bytes_per_second,receive_bytes_per_second,send_bytes_total,receive_bytes_total from v$systeminfo;"
metricstype = { send_bytes_total = "counter",receive_bytes_total = "counter" }

[[metric]]
context = "sysstat"
labels = [ "name" ]
metricsdesc = { value= "Gauge metric with count of  sysstat by DmService." }
request = " select name,stat_val as value from v$sysstat;"
metricstype = { value = "counter" }